### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by Niyowilson12** [De3vil/KLogger#3]
python logger.py
  File "/root/python-keylogger/KLogger/logger.py", line 50
    compile_command = ["wine", pyinstaller_path, "--onefile", "--noconsole" ,"--icon=+str("self.icon), self.filenampackeg]
                                                                                                    ^
SyntaxError: closing parenthesis ')' does not match opening parenthesis '['
whats wrong with the code?? on linux

**Comment by De3vil** [comment]
Done
